name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']

 

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'ryan0802demo' 
          # Container registry password
          password: 'bEQ3g77vFxxZDy8FSPc+60HKeu+N0hz1XosaG2nm8v+ACRCnVwV+' 
          # Container registry server url
          login-server: 'ryan0802demo.azurecr.io'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ryan0802demo.azurecr.io/hello-world-app:${{ github.sha }}
          file: ./Dockerfile

  deployToAKS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
